import test from 'node:test';import assert from 'node:assert/strict';
import {validateApplication,matchContractor,csvCell,escapeHtml} from '../lib/model.mjs';
import {sign,verify,equal,requireOrigin,requireAdmin} from '../lib/security.mjs';
process.env.TP_SESSION_SECRET='test-only-secret-not-valid-in-production-123456789';process.env.NODE_ENV='test';
const valid=()=>({company:'Example Company',contact:'Test Contact',email:'contact@example.com',zip:'34748',state:'FL',trade:'janitorial',serviceCounties:['Lake'],consent:true});
test('accepts minimum application without government experience',()=>{const p=validateApplication(valid());assert.equal(p.sam,'unknown');assert.equal(p.alertsOptIn,false);assert.equal(p.verification,'self-reported');});
test('requires affirmative consent',()=>assert.throws(()=>validateApplication({...valid(),consent:false})));
test('validates email',()=>assert.throws(()=>validateApplication({...valid(),email:'invalid'})));
test('validates ZIP format',()=>assert.throws(()=>validateApplication({...valid(),zip:'3474'})));
test('rejects unknown trade',()=>assert.throws(()=>validateApplication({...valid(),trade:'invented'})));
test('rejects executable website scheme',()=>assert.throws(()=>validateApplication({...valid(),website:'javascript:alert(1)'})));
test('rejects malformed arrays',()=>assert.throws(()=>validateApplication({...valid(),serviceCounties:'Lake'})));
test('rejects negative capacity',()=>assert.throws(()=>validateApplication({...valid(),maxProject:-1})));
test('rejects oversized description',()=>assert.throws(()=>validateApplication({...valid(),description:'a'.repeat(2001)})));
test('does not store supplied verification or arbitrary fields',()=>{const p=validateApplication({...valid(),verification:'verified',secret:'x'});assert.equal(p.verification,'self-reported');assert.equal(p.secret,undefined);});
test('does not require SAM for all subcontractors',()=>{const p=validateApplication(valid());const m=matchContractor(p,{trade:'janitorial',county:'Lake',role:'subcontractor'});assert.equal(m.decision,'Potential fit');});
test('unknown geographic fit is not manufactured from ZIP',()=>{const m=matchContractor(validateApplication(valid()),{county:'Broward'});assert.equal(m.locationMatch,false);});
test('capacity gaps are visible',()=>{const m=matchContractor(validateApplication({...valid(),maxProject:5000}),{value:20000});assert.ok(m.gaps.length);});
test('CSV formula defense',()=>{assert.ok(csvCell('=IMPORTXML(1)').startsWith('"\''));assert.ok(csvCell('+15555555555').startsWith('"\''));});
test('HTML escaping',()=>assert.equal(escapeHtml('<script>'),'&lt;script&gt;'));
test('tokens require valid signature, purpose and age',()=>{const token=sign({type:'intake',at:Date.now()});assert.ok(verify(token,'intake',60000));assert.equal(verify(token+'bad','intake',60000),null);assert.equal(verify(token,'admin',60000),null);assert.equal(verify(sign({type:'intake',at:Date.now()-120000}),'intake',60000),null);});
test('rejects foreign origin',()=>assert.throws(()=>requireOrigin({headers:{origin:'https://attacker.example'}})));
test('allows configured origin',()=>assert.doesNotThrow(()=>requireOrigin({headers:{origin:'https://tripointgs.com'}})));
test('admin requires valid cookie',()=>{assert.throws(()=>requireAdmin({headers:{}}));assert.doesNotThrow(()=>requireAdmin({headers:{cookie:'__Host-tp_admin='+sign({type:'admin',at:Date.now()})}}));});
test('secret equality is exact',()=>{assert.equal(equal('abc','abc'),true);assert.equal(equal('abc','abcd'),false);});
