import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createOpportunityService} from '../lib/opportunity-service.mjs';
import {createHandler} from '../api/opportunities.js';
import {sign} from '../lib/security.mjs';
import {HttpError} from '../lib/model.mjs';

process.env.TP_SESSION_SECRET='synthetic-tests-only-session-secret-123456789';
const clone=structuredClone;
function fixture({preview=true,enabled=false,sendError=false}={}) {
 const opportunities=new Map(),profiles=new Map(),calls=[];
 const p={id:randomUUID(),company:'Synthetic HVAC',contact:'Test Person',email:'synthetic@example.invalid',trade:'hvac',state:'FL',serviceCounties:['Lake'],crewSize:20,consent:true,verification:'verified',internalNotes:'Preserve internal review'};
 profiles.set(p.id,{record:clone(p),etag:1});
 const read=(map,id)=>{const item=map.get(id);if(!item)throw new HttpError(404,'missing');return clone(item);};
 const write=(map,record,etag)=>{const old=map.get(record.id);if(old?old.etag!==etag:etag!==undefined)throw new HttpError(409,'stale etag');map.set(record.id,{record:clone(record),etag:(old?.etag||0)+1});};
 const store={readOpportunity:async id=>read(opportunities,id),saveOpportunity:async(r,e)=>write(opportunities,r,e),pageOpportunities:async()=>({records:[...opportunities.values()].map(v=>clone(v.record)),hasMore:false}),readProfile:async id=>read(profiles,id),saveProfile:async(r,e)=>write(profiles,r,e),pageProfiles:async()=>({records:[...profiles.values()].map(v=>clone(v.record)),hasMore:false})};
 const delivery={configuration:()=>({preview,enabled}),send:async message=>{calls.push(clone(message));if(sendError)throw new Error('Synthetic timeout');return {providerId:'synthetic-provider-id'};}};
 const service=createOpportunityService(store,delivery);
 return {p,store,service,calls,async create(){return (await service.mutate({action:'create',opportunity:{title:'Synthetic internal opportunity',internal:{source:'INTERNAL SOURCE'},requirements:{trade:'hvac',crewSize:6},disclosure:{summary:'Synthetic scope'},contacts:{injected:{status:'Sent'}}}})).opportunity;},async editProfile(patch){const {record,etag}=await store.readProfile(p.id);await store.saveProfile({...record,...patch},etag);}};
}
async function ready(f){let o=await f.create();o=(await f.service.mutate({action:'select',id:o.id,revision:o.revision,contractorIds:[f.p.id]})).opportunity;return (await f.service.mutate({action:'draft',id:o.id,revision:o.revision,contractorId:f.p.id})).opportunity;}
const approval=(o,p,extra={})=>({action:'approve-send',id:o.id,revision:o.revision,contractorId:p.id,draftId:o.contacts[p.id].draft.id,confirm:true,...extra});
async function response(f,o,changes=[]){return (await f.service.mutate({action:'record-response',id:o.id,revision:o.revision,contractorId:f.p.id,status:'Interested',confirmations:{availableStaff:6,availableCapacity:50000},profileChanges:changes})).opportunity;}
const errorStatus=status=>error=>error.status===status;
async function uncertain(f){const o=await ready(f);await assert.rejects(()=>f.service.mutate(approval(o,f.p)),errorStatus(502));return (await f.store.readOpportunity(o.id)).record;}
async function ageAttempt(f,o){const {record,etag}=await f.store.readOpportunity(o.id);record.contacts[f.p.id].approvedAt=new Date(Date.now()-61000).toISOString();await f.store.saveOpportunity(record,etag);return record;}
const reconciliation=(o,p,extra={})=>({action:'reconcile-delivery',id:o.id,revision:o.revision,contractorId:p.id,confirm:true,outcome:'accepted',providerId:'synthetic-confirmed-id',evidence:'Synthetic provider lookup confirms this outcome.',...extra});
test('reconciliation requires explicit evidence, approval and one-minute in-flight guard',async()=>{const f=fixture({preview:false,enabled:true,sendError:true});let o=await uncertain(f);await assert.rejects(()=>f.service.mutate(reconciliation(o,f.p)),errorStatus(409));o=await ageAttempt(f,o);for(const extra of [{confirm:false},{evidence:''},{evidence:'short'},{evidence:'x'.repeat(2001)},{outcome:'unknown'},{providerId:''}])await assert.rejects(()=>f.service.mutate(reconciliation(o,f.p,extra)),errorStatus(400));assert.equal(f.calls.length,1);assert.equal((await f.store.readOpportunity(o.id)).record.contacts[f.p.id].sendState,'uncertain');});
test('accepted reconciliation records Sent and provider reference without transport',async()=>{const f=fixture({preview:false,enabled:true,sendError:true});const o=await ageAttempt(f,await uncertain(f));const result=await f.service.mutate(reconciliation(o,f.p));const c=result.opportunity.contacts[f.p.id];assert.equal(c.status,'Sent');assert.equal(c.sendState,'sent');assert.equal(c.providerId,'synthetic-confirmed-id');assert.ok(c.sentAt);assert.equal(f.calls.length,1);await assert.rejects(()=>f.service.mutate(reconciliation(result.opportunity,f.p)),errorStatus(400));});
test('confirmed not-sent reconciliation requires a fresh draft and renewed approval',async()=>{const f=fixture({preview:false,enabled:true,sendError:true});const o=await ageAttempt(f,await uncertain(f));const originalDraft=o.contacts[f.p.id].draft;const result=await f.service.mutate(reconciliation(o,f.p,{outcome:'not-sent',providerId:undefined}));const c=result.opportunity.contacts[f.p.id];assert.equal(c.status,'Not Contacted');assert.equal(c.draft,undefined);assert.equal(c.history.at(-1).draft.id,originalDraft.id);await assert.rejects(()=>f.service.mutate({...approval(o,f.p),revision:result.opportunity.revision}),errorStatus(400));const regenerated=await f.service.mutate({action:'draft',id:o.id,revision:result.opportunity.revision,contractorId:f.p.id});assert.notEqual(regenerated.opportunity.contacts[f.p.id].draft.id,originalDraft.id);assert.equal(regenerated.opportunity.contacts[f.p.id].status,'Draft Ready');await assert.rejects(()=>f.service.mutate(approval(regenerated.opportunity,f.p,{confirm:false})),errorStatus(400));assert.equal(f.calls.length,1);});
test('normal unattempted drafts cannot be marked sent through reconciliation',async()=>{const f=fixture(),o=await ready(f);await assert.rejects(()=>f.service.mutate(reconciliation(o,f.p)),errorStatus(400));assert.equal(f.calls.length,0);assert.equal((await f.store.readOpportunity(o.id)).record.contacts[f.p.id].status,'Draft Ready');});

test('simultaneous approval and rejection cannot disagree with permanent profile outcome',async()=>{for(const first of ['approve','reject']){const f=fixture();let o=await ready(f);o=await response(f,o,[{field:'crewSize',proposedValue:26,evidence:'Synthetic workforce correction'}]);const updateId=o.pendingUpdates[0].id;const review=decision=>f.service.mutate({action:'review-update',id:o.id,revision:o.revision,updateId,decision});const results=await Promise.allSettled([review(first),review(first==='approve'?'reject':'approve')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);const final=(await f.store.readOpportunity(o.id)).record,p=(await f.store.readProfile(f.p.id)).record;assert.equal(final.pendingUpdates[0].status,first==='approve'?'approved':'rejected');assert.equal(p.crewSize,first==='approve'?26:20);}});
test('failed profile write leaves reserved approval retryable and forbids conflicting rejection',async()=>{const f=fixture();let o=await ready(f);o=await response(f,o,[{field:'crewSize',proposedValue:26,evidence:'Synthetic workforce correction'}]);const updateId=o.pendingUpdates[0].id,originalSave=f.store.saveProfile;let writes=0;f.store.saveProfile=async(...args)=>{writes++;if(writes===1)throw new Error('Synthetic profile storage failure');return originalSave(...args);};const review=(revision,decision='approve')=>f.service.mutate({action:'review-update',id:o.id,revision,updateId,decision});await assert.rejects(()=>review(o.revision),/Synthetic profile storage failure/);const reserved=(await f.store.readOpportunity(o.id)).record;assert.equal(reserved.pendingUpdates[0].status,'applying');assert.equal((await f.store.readProfile(f.p.id)).record.crewSize,20);await assert.rejects(()=>review(reserved.revision,'reject'),errorStatus(409));const result=await review(reserved.revision);assert.equal(result.opportunity.pendingUpdates[0].status,'approved');const p=(await f.store.readProfile(f.p.id)).record;assert.equal(p.crewSize,26);assert.equal(p.profileUpdateAudit.length,1);assert.equal(writes,2);});
test('retry after final opportunity write fails does not apply profile twice',async()=>{const f=fixture();let o=await ready(f);o=await response(f,o,[{field:'crewSize',proposedValue:26,evidence:'Synthetic correction'}]);const updateId=o.pendingUpdates[0].id,originalSave=f.store.saveOpportunity;let failOnce=true;f.store.saveOpportunity=async(record,etag)=>{if(failOnce&&record.pendingUpdates[0]?.status==='approved'){failOnce=false;throw new Error('Synthetic finalization failure');}return originalSave(record,etag);};await assert.rejects(()=>f.service.mutate({action:'review-update',id:o.id,revision:o.revision,updateId,decision:'approve'}),/Synthetic finalization failure/);const reserved=(await f.store.readOpportunity(o.id)).record;assert.equal(reserved.pendingUpdates[0].status,'applying');assert.equal((await f.store.readProfile(f.p.id)).record.crewSize,26);const result=await f.service.mutate({action:'review-update',id:o.id,revision:reserved.revision,updateId,decision:'approve'});assert.equal(result.opportunity.pendingUpdates[0].status,'approved');assert.equal((await f.store.readProfile(f.p.id)).record.profileUpdateAudit.length,1);});

test('create discards imported contacts, matches and delivery state',async()=>{const f=fixture();const o=await f.create();assert.deepEqual(o.contacts,{});assert.deepEqual(o.pendingUpdates,[]);assert.equal(f.calls.length,0);});
test('manual selection and explicit current draft approval are mandatory',async()=>{const f=fixture({preview:false,enabled:true});let o=await f.create();await assert.rejects(()=>f.service.mutate({action:'draft',id:o.id,revision:o.revision,contractorId:f.p.id}),errorStatus(400));o=await ready(f);await assert.rejects(()=>f.service.mutate(approval(o,f.p,{confirm:false})),errorStatus(400));await assert.rejects(()=>f.service.mutate(approval(o,f.p,{draftId:randomUUID()})),errorStatus(400));assert.equal(f.calls.length,0);});
test('preview cannot send even when injected configuration reports enabled',async()=>{const f=fixture({preview:true,enabled:true}),o=await ready(f);await assert.rejects(()=>f.service.mutate(approval(o,f.p)),errorStatus(503));const r=await f.service.mutate(approval(o,f.p,{action:'test-draft'}));assert.equal(r.simulated,true);assert.equal(r.opportunity.contacts[f.p.id].status,'Draft Ready');assert.equal(f.calls.length,0);});
test('profile or recipient changes invalidate approved snapshot',async()=>{for(const patch of [{crewSize:21},{email:'different@example.invalid'},{consent:false}]){const f=fixture({preview:false,enabled:true}),o=await ready(f);await f.editProfile(patch);await assert.rejects(()=>f.service.mutate(approval(o,f.p)),errorStatus(409));assert.equal(f.calls.length,0);}});
test('concurrent approval sends once through an injected transport only',async()=>{const f=fixture({preview:false,enabled:true}),o=await ready(f);const results=await Promise.allSettled([f.service.mutate(approval(o,f.p)),f.service.mutate(approval(o,f.p))]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(f.calls.length,1);const current=(await f.store.readOpportunity(o.id)).record;assert.equal(current.contacts[f.p.id].status,'Sent');assert.ok(!JSON.stringify(f.calls).includes('INTERNAL SOURCE'));await assert.rejects(()=>f.service.mutate(approval(current,f.p)),errorStatus(400));assert.equal(f.calls.length,1);});
test('provider failure is uncertain and blocks retries and other mutations',async()=>{const f=fixture({preview:false,enabled:true,sendError:true}),o=await ready(f);await assert.rejects(()=>f.service.mutate(approval(o,f.p)),errorStatus(502));const current=(await f.store.readOpportunity(o.id)).record;assert.equal(current.contacts[f.p.id].sendState,'uncertain');await assert.rejects(()=>f.service.mutate(approval(current,f.p)),errorStatus(409));await assert.rejects(()=>f.service.mutate({action:'select',id:o.id,revision:current.revision,contractorIds:[]}),errorStatus(409));assert.equal(f.calls.length,1);});
test('responses keep company workforce separate and queue changed fields for explicit approval',async()=>{const f=fixture();let o=await ready(f);o=await response(f,o,[{field:'crewSize',proposedValue:26,evidence:'Synthetic reply: company workforce 26, available 6'}]);assert.equal((await f.store.readProfile(f.p.id)).record.crewSize,20);assert.equal(o.contacts[f.p.id].confirmations.availableStaff,6);assert.equal(o.pendingUpdates[0].status,'pending');assert.equal(o.pendingUpdates[0].oldValue,20);o=(await f.service.mutate({action:'review-update',id:o.id,revision:o.revision,updateId:o.pendingUpdates[0].id,decision:'approve'})).opportunity;const p=(await f.store.readProfile(f.p.id)).record;assert.equal(p.crewSize,26);assert.equal(p.verification,'verified');assert.equal(p.internalNotes,f.p.internalNotes);assert.equal(p.needsReverification.crewSize,true);assert.equal(p.profileUpdateAudit.length,1);assert.equal(o.contacts[f.p.id].confirmations.availableStaff,6);assert.equal(o.pendingUpdates[0].status,'approved');});
test('stale profile update approval cannot overwrite newer company data',async()=>{const f=fixture();let o=await ready(f);o=await response(f,o,[{field:'crewSize',proposedValue:26,evidence:'Synthetic change'}]);await f.editProfile({crewSize:30});await assert.rejects(()=>f.service.mutate({action:'review-update',id:o.id,revision:o.revision,updateId:o.pendingUpdates[0].id,decision:'approve'}),errorStatus(409));assert.equal((await f.store.readProfile(f.p.id)).record.crewSize,30);assert.equal((await f.store.readOpportunity(o.id)).record.pendingUpdates[0].status,'pending');});
test('rejected changes and protected-field proposals do not mutate profiles',async()=>{const f=fixture();let o=await ready(f);await assert.rejects(()=>response(f,o,[{field:'verification',proposedValue:'verified',evidence:'Synthetic reply'}]),errorStatus(400));o=await response(f,o,[{field:'crewSize',proposedValue:26,evidence:'Synthetic reply'}]);o=(await f.service.mutate({action:'review-update',id:o.id,revision:o.revision,updateId:o.pendingUpdates[0].id,decision:'reject'})).opportunity;assert.equal(o.pendingUpdates[0].status,'rejected');assert.equal((await f.store.readProfile(f.p.id)).record.crewSize,20);});

async function request(handler,{method='GET',url='/api/opportunities',token,origin,body}={}){const headers={'content-type':'application/json',...(token?{cookie:'__Host-tp_admin='+token}:{}),...(origin?{origin}:{})};const res={headers:{},setHeader(k,v){this.headers[k]=v;},end(v){this.payload=JSON.parse(v);}};await handler({method,url,headers,body},res);return res;}
test('every private route operation rejects anonymous and intake-purpose cookies before access',async()=>{let accessed=0;const handler=createHandler({get:async()=>{accessed++;},mutate:async()=>{accessed++;}});for(const token of [undefined,sign({type:'intake',at:Date.now()})]){for(const url of ['/api/opportunities','/api/opportunities?id='+randomUUID(),'/api/opportunities?id='+randomUUID()+'&matches=1'])assert.equal((await request(handler,{url,token})).statusCode,401);for(const action of ['create','update','select','draft','approve-send','test-draft','record-response','review-update','reconcile-delivery'])assert.equal((await request(handler,{method:'POST',token,origin:'https://tripointgs.com',body:{action}})).statusCode,401);}assert.equal(accessed,0);});
test('authenticated mutations reject foreign or missing origins; authorized reads are private',async()=>{let mutations=0;const handler=createHandler({get:async()=>({opportunities:[]}),mutate:async()=>{mutations++;return {};}}),token=sign({type:'admin',at:Date.now()});for(const origin of [undefined,'https://attacker.example'])assert.equal((await request(handler,{method:'POST',token,origin,body:{action:'create'}})).statusCode,403);assert.equal(mutations,0);const read=await request(handler,{token});assert.equal(read.statusCode,200);assert.equal(read.headers['Cache-Control'],'no-store, private');assert.equal(read.headers['X-Robots-Tag'],'noindex, nofollow');assert.equal((await request(handler,{method:'POST',token,origin:'https://tripointgs.com',body:{action:'create'}})).statusCode,200);assert.equal(mutations,1);});
