import test from 'node:test';
import assert from 'node:assert/strict';
import {parseOpportunityImport} from '../assets/opportunity-import.mjs';
import {validateOpportunity} from '../lib/opportunities.mjs';
import {SERVICE_IDS} from '../lib/model.mjs';

const nested=()=>({requisition_id:'REQ-SYNTHETIC-0001',source:{platform:'Synthetic portal',source_url:'https://example.invalid/solicitation',date_found:'2026-09-01',last_checked:'2026-09-02'},solicitation:{title:'',solicitation_number:'SYN-001',agency:'Synthetic Agency',department:'Facilities',solicitation_type:'RFQ',procurement_method:'Sealed quote',set_aside:'Review required',naics_code:'000000',psc_code:'TEST',place_of_performance:{address:'Synthetic site',city:'Test City',state:'fl',zip:'00000',country:'US'},posted_date:'2026-09-01',questions_due:'2026-09-15',bid_due:'2026-09-30T15:00:00-04:00',anticipated_award_date:'2026-10-10',contract_start_date:'2026-11-01',contract_end_date:'2027-10-31',option_years:2},scope:{summary:'Synthetic HVAC scope',work_description:'Inspect cooling units',deliverables:['Inspection report'],estimated_quantity:5,service_frequency:'Monthly',working_hours:{start:'08:00',end:'17:00'}},financials:{estimated_contract_value:50000,budget_ceiling:60000,bonds:['Review bid bond'],insurance_requirements:['General liability limits require review'],payment_terms:'Net 30'},compliance:{sam_registration_required:true,cage_code_required:true,uei_required:true,licenses_required:['Applicable trade license'],certifications_required:['Review certificate'],experience_requirements:'Three comparable jobs',references_required:3,background_checks_required:true,security_clearance_required:false,local_registration_required:true,other_requirements:['Site inspection']},submission:{method:'Portal',portal:'https://example.invalid/submission',email:'synthetic@example.invalid',required_forms:['Form A'],required_documents:['Pricing'],pricing_format:'Schedule',signature_required:true},contacts:[{name:'Synthetic Officer',email:'synthetic@example.invalid'}],documents:[{name:'Synthetic attachment',url:'https://example.invalid/attachment'}],tri_point_review:{bid_status:'Review',bid_no_bid_reason:'Needs scope check',fit_notes:'Potential fit',major_risks:['Schedule conflict'],questions_to_ask:['Site access?'],pricing_notes:'Validate labor',estimated_cost:30000,target_bid_price:45000,estimated_gross_profit:15000,estimated_margin_percent:33.3},subcontractor_matching:{needed:true,trade_categories:['hvac'],service_area:'Lake County',minimum_requirements:['Six available staff'],matched_contractors:['NEVER IMPORT MATCH'],selected_for_outreach:['NEVER SELECT']},outreach:{enabled:true,email_subject:'NEVER EMAIL',email_template:'NEVER EMAIL BODY',include_opportunity_details:true},internal:{assigned_to:'Synthetic Staff',priority:'Medium',notes:'INTERNAL NOTE',tags:['synthetic']}});

test('nested requisition becomes valid private opportunity with title fallback and empty disclosure',()=>{const input=nested(),{opportunity:o,warnings}=parseOpportunityImport(JSON.stringify(input));assert.equal(o.title,input.requisition_id);assert.equal(o.requirements.trade,'hvac');assert.equal(o.requirements.state,'FL');assert.equal(o.requirements.sam,false);assert.equal(o.requirements.insurance,false);assert.equal(o.requirements.role,'subcontractor');assert.ok(Object.values(o.disclosure).every(v=>v===''));assert.match(warnings.join(' '),/temporary title/);assert.match(warnings.join(' '),/Prime registration/);assert.doesNotThrow(()=>validateOpportunity(o));assert.equal(o.internal.solicitationUrl,input.source.source_url);assert.equal(o.internal.deadline,input.solicitation.bid_due);assert.match(o.internal.source,/last_checked/);assert.match(o.review.fullScope,/Synthetic attachment/);assert.match(o.review.fullScope,/Synthetic Officer/);assert.match(o.review.fullScope,/estimated_quantity/);assert.match(o.review.compliance,/sam_registration_required/);assert.match(o.review.compliance,/required_forms/);assert.match(o.internal.pricing,/insurance_requirements/);assert.match(o.review.pricingProfitability,/30000/);assert.match(o.internal.margins,/33.3/);assert.match(o.review.risksQuestionsDeadlines,/Site access/);assert.match(o.internal.bidStrategy,/INTERNAL NOTE/);assert.equal(o.contacts,undefined);assert.equal(o.pendingUpdates,undefined);assert.equal(o.outreach,undefined);assert.ok(!JSON.stringify(o).includes('NEVER'));});
test('canonical and fenced single-opportunity wrapper use field allowlists',()=>{const raw={opportunity:{title:'Synthetic canonical',requirements:{trade:'hvac',sam:true,role:'prime',crewSize:6,unknown:'DROP'},internal:{source:'private',unknown:'DROP'},review:{bidNoBid:'Review'},disclosure:{summary:'Explicitly chosen safe summary'},contacts:{anything:{status:'Sent'}},id:'forged',draft:{body:'DROP'}}};const {opportunity:o,warnings}=parseOpportunityImport('```json\n'+JSON.stringify(raw)+'\n```');assert.equal(o.title,'Synthetic canonical');assert.equal(o.requirements.sam,true);assert.equal(o.disclosure.summary,'Explicitly chosen safe summary');assert.equal(o.contacts,undefined);assert.equal(o.id,undefined);assert.ok(!JSON.stringify(o).includes('DROP'));assert.ok(warnings.length);assert.doesNotThrow(()=>validateOpportunity(o));});
test('empty nested title without fallback explains how to repair input',()=>{const input=nested();delete input.requisition_id;assert.throws(()=>parseOpportunityImport(input),/Add a title at title or solicitation.title/);input.solicitation.title='Synthetic title';assert.equal(parseOpportunityImport(input).opportunity.title,'Synthetic title');});
test('unknown and multiple trades remain private without guessing',()=>{for(const categories of [['HVAC repair'],['hvac','plumbing']]){const input=nested();input.subcontractor_matching.trade_categories=categories;const {opportunity:o,warnings}=parseOpportunityImport(input);assert.equal(o.requirements.trade,'');assert.match(o.review.suppliersSubcontractors,new RegExp(categories[0]));assert.match(warnings.join(' '),/manual review/);}});
test('all authoritative service IDs remain supported by browser-safe parser',()=>{for(const trade of SERVICE_IDS){const input=nested();input.subcontractor_matching.trade_categories=[trade];assert.equal(parseOpportunityImport(input).opportunity.requirements.trade,trade);}});
test('oversized private or canonical content rejects instead of truncating',()=>{const input=nested();input.scope.work_description='x'.repeat(6001);assert.throws(()=>parseOpportunityImport(input),/review.fullScope exceeds 6000 characters.*no content was truncated/);assert.throws(()=>parseOpportunityImport({title:'Synthetic',review:{compliance:'x'.repeat(6001)}}),/review.compliance exceeds 6000/);assert.throws(()=>parseOpportunityImport({title:'x'.repeat(181)}),/title exceeds 180/i);});
test('malformed JSON sections and formats receive actionable errors',()=>{assert.throws(()=>parseOpportunityImport('not json'),/not valid JSON/);assert.throws(()=>parseOpportunityImport('[]'),/JSON object/);assert.throws(()=>parseOpportunityImport({title:'Test',requirements:[]}),/requirements must be a JSON object/);const input=nested();input.subcontractor_matching.trade_categories='hvac';assert.throws(()=>parseOpportunityImport(input),/must be an array/);});
test('full state names retained privately and never coerced to matching state',()=>{const input=nested();input.solicitation.place_of_performance.state='Florida';const {opportunity:o,warnings}=parseOpportunityImport(input);assert.equal(o.requirements.state,'');assert.match(o.review.fullScope,/Florida/);assert.match(warnings.join(' '),/two-letter code/);});
test('submission_portal is preferred with portal accepted as a legacy alias',()=>{const input=nested();assert.equal(parseOpportunityImport(input).opportunity.internal.procurementPortal,input.submission.portal);input.submission.submission_portal='https://example.invalid/preferred';assert.equal(parseOpportunityImport(input).opportunity.internal.procurementPortal,input.submission.submission_portal);});
test('canonical requirements reject types and values the form might otherwise silently coerce',()=>{for(const [key,value] of [['sam','false'],['insurance',1],['workersComp','true'],['licensed',{}],['trade','HVAC repair'],['role','agency'],['state','Florida'],['county','x'.repeat(101)],['crewSize',-1],['crewSize',100001],['maxProject',100000001],['maxProject',2.5],['crewSize',true],['availability',[]]])assert.throws(()=>parseOpportunityImport({title:'Synthetic',requirements:{[key]:value}}),new RegExp(`requirements\\.${key}`));const {opportunity:o}=parseOpportunityImport({title:'Synthetic',requirements:{state:'fl',crewSize:'6',maxProject:'50000',sam:false}});assert.equal(o.requirements.state,'FL');assert.equal(o.requirements.crewSize,6);assert.equal(o.requirements.maxProject,50000);assert.equal(o.requirements.sam,false);assert.doesNotThrow(()=>validateOpportunity(o));});
test('blank working-hours template does not create an availability requirement',()=>{const input=nested();input.solicitation.contract_start_date='';input.solicitation.contract_end_date='';input.scope.working_hours={day_shift:'',night_shift:' ',weekends_required:false,holidays_required:false};const {opportunity:o}=parseOpportunityImport(input);assert.equal(o.requirements.availability,'');assert.match(o.review.fullScope,/weekends_required/);assert.match(o.review.fullScope,/holidays_required/);});
test('explicit dates shifts and true schedule flags produce readable availability',()=>{const input=nested();input.scope.working_hours={day_shift:'Monday through Friday',night_shift:'',start:'08:00',end:'17:00',weekends_required:true,holidays_required:true};const {opportunity:o}=parseOpportunityImport(input);assert.equal(o.requirements.availability,'Contract start: 2026-11-01\nContract end: 2027-10-31\nDay shift: Monday through Friday\nStart time: 08:00\nEnd time: 17:00\nWeekend work required\nHoliday work required');assert.ok(!/[{}"]/.test(o.requirements.availability));assert.match(o.review.fullScope,/day_shift/);});
