import {createHmac,createHash,timingSafeEqual,randomUUID} from 'node:crypto';
import {HttpError} from './model.mjs';
export function secret(){const x=process.env.TP_SESSION_SECRET;if(!x||x.length<32)throw new HttpError(503,'The service is temporarily unavailable. Please email info@tripointgs.com.');return x;}
export const digest=(v)=>createHmac('sha256',secret()).update(String(v)).digest('hex');
export function equal(a,b){return timingSafeEqual(createHash('sha256').update(String(a||'')).digest(),createHash('sha256').update(String(b||'')).digest());}
export function sign(payload){const encoded=Buffer.from(JSON.stringify(payload)).toString('base64url');return encoded+'.'+digest(encoded);}
export function verify(token,type,maxAge){if(typeof token!=='string'||token.length>1000)return null;const [encoded,sig,...extra]=token.split('.');if(extra.length||!encoded||!equal(sig,digest(encoded)))return null;try{const p=JSON.parse(Buffer.from(encoded,'base64url').toString());if(p.type!==type||!Number.isFinite(p.at)||p.at>Date.now()+30000||Date.now()-p.at>maxAge)return null;return p;}catch{return null;}}
export function challenge(){return sign({type:'intake',id:randomUUID(),at:Date.now()});}
export function requireOrigin(req){const allowed=new Set([process.env.SITE_ORIGIN||'https://tripointgs.com','https://www.tripointgs.com']);for(const k of ['VERCEL_URL','VERCEL_BRANCH_URL'])if(process.env[k])allowed.add('https://'+process.env[k]);if(process.env.NODE_ENV==='test')allowed.add('http://localhost:3000');if(!allowed.has(req.headers.origin))throw new HttpError(403,'This request must be submitted from the Tri-Point website.');}
export function requireAdmin(req){const cookie=req.headers.cookie||'';const value=cookie.split(';').map(x=>x.trim()).find(x=>x.startsWith('__Host-tp_admin='))?.slice('__Host-tp_admin='.length);if(!verify(value,'admin',8*3600000))throw new HttpError(401,'Please sign in to the private contractor directory.');}
export function setAdminCookie(res,active){res.setHeader('Set-Cookie','__Host-tp_admin='+(active?sign({type:'admin',at:Date.now()}):'')+'; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age='+(active?'28800':'0'));}
export async function body(req,maxBytes=16384){if(!String(req.headers['content-type']||'').startsWith('application/json'))throw new HttpError(415,'Please send a JSON request.');if(Number(req.headers['content-length']||0)>maxBytes)throw new HttpError(413,'The submitted form is too large.');let b=req.body;if(b===undefined){const chunks=[];let size=0;for await(const chunk of req){size+=Buffer.byteLength(chunk);if(size>maxBytes)throw new HttpError(413,'The submitted form is too large.');chunks.push(chunk);}b=Buffer.concat(chunks).toString();}if(Buffer.isBuffer(b))b=b.toString();if(typeof b==='string'){if(Buffer.byteLength(b)>maxBytes)throw new HttpError(413,'The submitted form is too large.');try{b=JSON.parse(b);}catch{throw new HttpError(400,'The submitted form could not be read.');}}if(!b||typeof b!=='object'||Array.isArray(b)||Buffer.byteLength(JSON.stringify(b))>maxBytes)throw new HttpError(400,'The submitted form could not be read.');return b;}
export function send(res,status,data){res.setHeader('Cache-Control','no-store, private');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Robots-Tag','noindex, nofollow');res.setHeader('Content-Type','application/json; charset=utf-8');res.statusCode=status;res.end(JSON.stringify(data));}
export function fail(res,e){if(!(e instanceof HttpError))console.error('Network request failed',e?.name||'Error');send(res,e.status||503,{error:e instanceof HttpError?e.message:'The service is temporarily unavailable. Please try again or email info@tripointgs.com.'});}
